language: python

python:
  - "2.7"
  - "3.8"
  - "pypy"
  - "pypy3"
services:
  - docker

before_install:
  - docker build -t riipeckx/bai-systems-smart-api-rest-python:latest .

install:
  - pip install -r requirements.txt
  - pip install .
on:
    branch: master